GOOGLE_API_KEY:
  AIzaSyBOti4mM-6x9WDnZIjIeyEU21OpBXqWBgw
PUSHBULLET_KEY:
  v1Egi9BFtSgXZZ6Ae6Enm0alIv7zY6U5YlujxepFaLriu
PUSHBULLET_ID:
  ujxepFaLriusjAmnZB0OAK
DEVICE_NAME:
  Linux
KEYWORD:
  jarvis,okay google,mark
WOLFRAM_KEY:
  Q59EW4-UEL27J79UK
COORDINATES:
  LAT:
    40.9142
  LONG:
    -73.1162
